### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by paulolieuthier** [sindresorhus/github-notifier-firefox#4]
This extension is really helpful, thanks for it! However, it stopped working one or two weeks ago with Firefox Developer Edition (37.0a2 now) running on Linux. Tell me how I can be helpful.

**Comment by sindresorhus** [comment]
The addon developer story for Firefox is horrible and I don't have the energy or time to set up the addon environment and look into it in the near term. So you're probably better off using something else unless you or anyone submits a PR.

**Comment by paulolieuthier** [comment]
Thanks for the fix! How long is it going to take to get the update? I'm not sure how to build it.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/github-notifier-firefox/pull/5#issuecomment-71320657

**Comment by seleznev** [comment]
@paulolieuthier, please try to install [1.3b1 version](https://addons.mozilla.org/en-US/firefox/addon/github-notifier/versions/?page=1#version-1.3b1) from AMO.

Also if you really need white icon, you can unpack .xpi from AMO (it's just zip archive), change icon and pack it again.

**Comment by paulolieuthier** [comment]
Very nice, thank you. Working perfectly now.
