### ISSUE TITLE
Version numbering

### ISSUE THREAD

**Issue by GizMecano** [sindresorhus/github-notifier-firefox#8]
It's not an actual issue but rather a really minor question, I admit.

I have noticed that the [`addons.mozilla.org` page](https://addons.mozilla.org/en/firefox/addon/github-notifier/) indicates that the current version is `1.4.1` (signed and released on 5th April 2015) when the present repository seems to point that [the last release](https://github.com/sindresorhus/github-notifier-firefox/releases/tag/1.4) (committed the same day) is `1.4` (may be for `1.4.0`).

May be you could eventually clarify this versioning?

**Comment by sindresorhus** [comment]
// @seleznev

**Comment by seleznev** [comment]
> May be you could eventually clarify this versioning?

It's result of automatic sign process on AMO. We didn't change anything. All new versions will have a correct version number.

**Comment by GizMecano** [comment]
Thanks for your answer.
